### ISSUE TITLE
global_vars should be available in imported modules

### ISSUE THREAD

**Issue by trel** [irods/irods_rule_engine_plugin_python#183]
From iRODS-Chat:
 - https://groups.google.com/g/irod-chat/c/pWAnxKIVqr0/m/mCNeGw5eAwAJ

The `global_vars` dict is not available in imported python modules.  This prevents imported python rules from being able to be called directly from `irule` with parameters.

---

A workaround in the meantime is to provide an empty-forwarding-function in core.py that calls the imported function with the global_vars dict.

core.py
```
from myRules import the_function as py_the_function

def the_function(rule_args, callback, rei):
    py_the_function(global_vars, callback, rei)
```

myRules.py
```
def the_function(rule_args, callback, rei):
    callback.writeLine('serverLog', 'py_the_function rule_args ['+str(rule_args)+']') 
```

Then....
```
$ irule -r irods_rule_engine_plugin-python-instance the_function '*var_1="e"%*var_2="f"%*var_3="g"' ruleExecOut
```
produces this in the serverLog...
```
{
  "log_category": "legacy",
  "log_level": "info",
  "log_message": "writeLine: inString = py_the_function rule_args [{'*var_1': '\"e\"', '*var_2': '\"f\"', '*var_3': '\"g\"'}]\n",
  "request_api_name": "EXEC_MY_RULE_AN",
  "request_api_number": 625,
  "request_api_version": "d",
  "request_client_user": "rods",
  "request_host": "127.0.0.1",
  "request_proxy_user": "rods",
  "request_release_version": "rods4.3.1",
  "server_host": "xxx.xxx.xxx.xxx",
  "server_pid": 4091083,
  "server_timestamp": "2024-01-04T15:29:52.981Z",
  "server_type": "agent",
  "server_zone": "tempZone"
}
```

**Comment by korydraughn** [comment]
First, the reason `global_vars` isn't available to modules imported by core.py is because `global_vars` is attached to the `core` module's namespace. Therefore, `global_vars` isn't visible in other modules. The following is the reason behind this behavior. Notice lines 744-748.
https://github.com/irods/irods_rule_engine_plugin_python/blob/674f5657e6d5d67c886684c32f9a9236884944c7/src/main.cpp#L740-L759

With that said, we've landed on two ideas ...
- Provide an importable Boost.Python module _(just like irods_errors and irods_types)_ which provides access to a `global_vars`-like object
    - This would allow any user python code to import the module on demand
    - The module would be implemented in C++
- Or, attach a `global_vars`-like object to the `__builtins__` module via Boost.Python
    - This approach would make the object available at all times
    - This approach doesn't require the user's code to import anything

**Again, these are just ideas. We'll investigate and share updates as we learn more.**

Regardless of the solution, `global_vars` as it is today, would be marked **deprecated** and users would be urged to use the new object (which would have a more appropriate name). At this time, the current choices for the name are _(in no particular order)_ ...
- `irods_global_vars`
- `irods_rule_vars`
- `irods_rule_input_output`

We're open to alternative names too.

**Comment by trel** [comment]
idea 1 (module) may not be possible due to compile-time vs run-time availability of the information we want to provide.

idea 2 (builtins) seems pretty clean.

**Comment by SwooshyCueb** [comment]
I've just done a quick and dirty test of idea 2 and it seems to work very well and very cleanly, will submit a draft PR soon

**Comment by SwooshyCueb** [comment]
Looks like we've got some references to `global_vars` in the tests in the main irods repo, so we need to make sure those are updated before this issue is closed https://github.com/search?q=repo%3Airods%2Firods%20global_vars&type=code

**Comment by alanking** [comment]
Any chance we can/will include this in a 4.3.1.1?

**Comment by korydraughn** [comment]
Is something other than tests holding us back from doing that?

**Comment by SwooshyCueb** [comment]
Not that I'm aware

**Comment by korydraughn** [comment]
Agreed. We can still test against 4.3.1. If all we need to do is tweak tests, then we can add a commit to an iRODS 4.3.1 build and run them with the updated plugin.

**Comment by SwooshyCueb** [comment]
Are we good to close this issue?

**Comment by korydraughn** [comment]
We need to see the changes work with a 4.3.1 server. Has that happened?

Will add this as a discussion topic for tomorrow.

**Comment by SwooshyCueb** [comment]
Finished running tests against 4.3.1. Everything passes except for the expected failures.

**Comment by korydraughn** [comment]
Excellent. Please close when ready.
